LAB8: sas ssim
CC    = gcc 
CCOPT = -Wall -W -ansi -Werror -pedantic -g 

sas: assem.c assemmacros.h
	$(CC) $(CPOPT) assem.c -o sas 

ssim: simulator.c simmacros.h
	$(CC) $(CPOPT) simulator.c -o ssim
